coreKnowledgeSamples = [
    "What is risk in insurance?",
    "Explain the concept of underwriting in insurance.",
    "What is a beneficiary in a life insurance policy?",
    "Define premium and how it is calculated.",
    "How does the law of large numbers apply to insurance?",
    "What is adverse selection in insurance?",
    "What is the difference between term and whole life insurance?",
    "Explain the principle of insurable interest.",
    "How does group insurance differ from individual insurance?",
    "What is the free look period?",
    "Describe what a surrender value is.",
    "What topics are covered in LOMA 281?",
    "What topics are covered in LOMA 291?",
]

offTopicSamples = [
    "hello",
    "Hi there!",
    "What is the weather today?",
    "What is the capital of France?",
    "Who won the World Cup?",
    "Recommend a good movie to watch.",
    "Tell me a joke.",
    "Can you help me write an email to my boss?",
    "How do I fix a bug in Python?",
    "What stocks should I buy?",
    "How do I make pasta carbonara?",
    "What's trending on social media today?",
]
